# extract epd database from pgn generated by cutechess for tuning
# cutechess/cutechess-cli -each tc=1/1+0.08 proto=uci -engine cmd=chess-2/chess2_latest book=openings.bin -engine cmd=chess-2/chess2_other book=openings.bin -rounds 60000 -concurrency 4 -pgnout games_fast.pgn  -recover &
import chess.pgn

fn = 'games_fast.pgn'

with open(fn, encoding='utf-8') as h:
    while True:
        game = chess.pgn.read_game(h)
        if game is None:
            break

        for node in game.mainline():
            comment = node.comment
            if comment=='book':
                pass
            elif comment.startswith('+100.00') or comment.startswith('-100.00'):
                pass
            else:
                fen = node.board().fen()
                result = game.headers[ 'Result' ]
                if result == '1-0' or result == '0-1' or result == '1/2-1/2':
                    print(f'{fen} {result}')
