name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cmocka
      run: sudo apt-get install -y libcmocka0 libcmocka-dev
    - name: make
      working-directory: test
      run: make
    - name: test
      working-directory: test
      run: ./test
